name: Build and Test

on:
  push:
    branches:
       main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Set your Java version here

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and Test with Gradle
        run: |
          ./gradlew clean test --stacktrace --info
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

