name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Set your Java version here

      - name: Build with Gradle
        run: |
          ./gradlew clean build --refresh-dependencies
        env:
          GRADLE_USER_HOME: ./gradle   # Optional: Set Gradle user home if needed

